### ISSUE TITLE
problems with join_ or i cant get it

### ISSUE THREAD

**Issue by OzodbekUSTECH** [OysterHQ/FastAPI-Production-Boilerplate#10]
join_ is not working well, i am trying to join_{'tasks'}, but i got the error

    query = query.filter(User.id == user_id)
            ^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'filter'

**Comment by iam-abbas** [comment]
This is because you’re not awaiting `query` when you declare `query` use `await`

**Comment by OzodbekUSTECH** [comment]
Sry, but same, probably i am stupid) But i just wanna get tasks of user by using relationship, not just foreignkey
here the code:
@user_router.get('/tasks')
async def get_tasks_for_user(
    user_id: int,
    user_controller: UserController = Depends(Factory().get_user_controller),
):
    user = await user_controller.get_user_tasks(user_id)
    return user.tasks
    
    async def get_user_tasks(self, user_id: int):
        user = await self.user_repository.get_by_id(user_id, join_={'tasks'})
        return user
      
  
   class UserRepository(BaseRepository[User]):
    """
    User repository provides all the database operations for the User model.
    """
    
    async def get_by_id(
        self, user_id: int, join_: set[str] | None = None
    ) -> User | None:
        """
        Get user by username.

        :param username: Username.
        :param join_: Join relations.
        :return: User.
        """
        
        query = await self._query(join_)
        query = await query.filter(User.id == user_id)
        return await self._one_or_none(query)
        
        
        
        btw you also dont use AWAIT here in your code

async def get_by_username(
        self, username: str, join_: set[str] | None = None
    ) -> User | None:
        """
        Get user by username.

        :param username: Username.
        :param join_: Join relations.
        :return: User.
        """
        query = await self._query(join_)
        query = query.filter(User.username == username)
        return await self._one_or_none(query)

**Comment by iam-abbas** [comment]
I see no mistake in your code, can you show the error log

**Comment by OzodbekUSTECH** [comment]
INFO:     127.0.0.1:60466 - "GET /v1/users/tasks?user_id=1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\home\production-refact\venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\home\production-refact\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\home\production-refact\venv\Lib\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "D:\home\production-refact\venv\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\home\production-refact\venv\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\home\production-refact\venv\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\home\production-refact\venv\Lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "D:\home\production-refact\venv\Lib\site-packages\starlette\middleware\authentication.py", line 48, in __call__
    await self.app(scope, receive, send)
  File "D:\home\production-refact\core\fastapi\middlewares\sqlalchemy.py", line 19, in __call__
    raise exception
  File "D:\home\production-refact\core\fastapi\middlewares\sqlalchemy.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\home\production-refact\core\fastapi\middlewares\response_logger.py", line 37, in __call__
    await self.app(scope, receive, _logging_send)
  File "D:\home\production-refact\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\home\production-refact\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\home\production-refact\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "D:\home\production-refact\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\home\production-refact\venv\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\home\production-refact\venv\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\home\production-refact\venv\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "D:\home\production-refact\venv\Lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\home\production-refact\venv\Lib\site-packages\fastapi\routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\home\production-refact\api\v1\users\users.py", line 78, in get_tasks_for_user
    user = await user_controller.get_user_tasks(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\home\production-refact\app\controllers\user.py", line 18, in get_user_tasks
    user = await self.user_repository.get_by_id(user_id, join_={'tasks'})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\home\production-refact\app\repositories\user.py", line 25, in get_by_id
    query = await query.filter(User.id == user_id)
                  ^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'filter'


here i get coroutine probably instead of model instance, not sure

```
async def _add_join_to_query(self, query: Select, join_: set[str]) -> Select:
        """
        Returns the query with the given join.

        :param query: The query to join.
        :param join_: The join to make.
        :return: The query with the given join.
        """
        return getattr(self, "_join_" + join_)(query)
```

**Comment by iam-abbas** [comment]
You don’t need `await` for filter. Only need it for `_query` before. 

`query = query.filter(User.id == user_id)`

This cloud be an issue with repo itself due to the latest package updates. I will check and deploy any fixes soon.

**Comment by OzodbekUSTECH** [comment]
ive removed await, but same error. Ok, thanks, i will wit for fixes :)

**Comment by dka58** [comment]
So I faced the same issue and finally got it to work. 
This solution is not ideal, which is why I didn't create a PR it needs some tweaking but it gets the job done.

1. The main issue is that a bunch of methods are defined using async but there are no asynchronous operations inside. So first off we make them synchronous (skipping the docstrings to compress the answer):
- Change all the methods
    ```python
    def _query( self, join_: set[str] | None = None, order_: dict | None = None,
    ) -> Select:
        query = select(self.model_class)
        query = self._maybe_join(query, join_)
        query = self._maybe_ordered(query, order_)

        return query
        
    def _maybe_join(self, query: Select, join_: set[str] | None = None) -> Select:
        if not join_:
            return query

        if not isinstance(join_, set):
            raise TypeError("join_ must be a set")

        return reduce(self._add_join_to_query, join_, query)

    def _maybe_ordered(self, query: Select, order_: dict | None = None) -> Select:
        if order_:
            if order_["asc"]:
                for order in order_["asc"]:
                    query = query.order_by(getattr(self.model_class, order).asc())
            else:
                for order in order_["desc"]:
                    query = query.order_by(getattr(self.model_class, order).desc())

        return query
        
        
    def _add_join_to_query(self, query: Select, join_: set[str]) -> Select:
        return getattr(self, f"_join_{join_}")(query)
        
    def _join_tasks(self, query: Select) -> Select:
        return query.options(joinedload(User.tasks))
        ```
- Change the call for join
    ```python
    query = self._query(join_)
     ```

After doing this, you'll no longer get coroutines when calling `query.filter(...)`, but you'll get an error from SQLAlchemy
```
sqlalchemy.exc.InvalidRequestError: The unique() method must be invoked on this Result, as it contains results that include joined eager loads against collections
```
You can read about this more [here](https://docs.sqlalchemy.org/en/20/orm/queryguide/relationships.html#joined-eager-loading)

2. To solve this error you can either modify your `_all()` method, or create a separate method:
```python
async def _all_unique(self, query: Select) -> list[ModelType]:
        result = await self.session.execute(query)
        return result.unique().scalars().all()
```
And then call it in the `get_by_username` method:
```python
async def get_by_username( self, username: str, join_: set[str] | None = None) -> User | None:
    query = await self._query(join_)
    query = query.filter(User.username == username)
    if join_ is not None:
        return await self.all_unique(query)
    return await self._one_or_none(query)
````
